Diberikan data test untuk kasus unguided praktikum minggu ini, lakukan identifikasi pada data tersebut apakah terdapat perbedaan karakteristik data train pada praktikum sebelumnya.

In [ ]:
import pandas as pd
train_features = pd.read_csv('train_features.csv')
test_features = pd.read_csv('test_features.csv')
train = pd.concat([train_features, test_features], axis=1)
print(train.head())

   tahun_kelahiran pendidikan status_pernikahan   pendapatan  \
0           1979.0    Sarjana   Rencana Menikah          NaN
1           1950.0    Sarjana   Rencana Menikah   84063000.0
2           1966.0    Sarjana           Menikah  127532564.0
3           1961.0   Magister   Rencana Menikah  165579620.0
4           1970.0    Sarjana   Rencana Menikah  117703159.0

   jumlah_anak_balita  jumlah_anak_remaja  terakhir_belanja  belanja_buah  \
0                 0.0                 1.0               NaN       50575.0
1                 NaN                 NaN              70.0        6069.0
2                 0.0                 0.0              45.0      117611.0
3                 0.0                 0.0              90.0      206346.0
4                 1.0                 1.0              78.0       90563.0

   belanja_daging  belanja_ikan  ...  terakhir_belanja  belanja_buah  \
0        260967.0       50575.0  ...              63.0      122277.0
1         44506.0       80920.0  ...              58.0       35761.0
2        265460.0       96341.0  ...              34.0        8092.0
3       1613901.0       27725.0  ...              82.0        4872.0
4        311757.0       40358.0  ...              28.0      343208.0

   belanja_daging  belanja_ikan  belanja_kue pembelian_diskon  pembelian_web  \
0        541399.0      214192.0      84305.0              4.0            6.0
1        353335.0       63365.0      41112.0              2.0            5.0
2         22253.0       30345.0      26299.0              2.0            0.0
3        126061.0           0.0       9745.0              3.0            5.0
4       1416462.0      236196.0     107776.0              0.0            1.0

   pembelian_toko keluhan tanggal_menjadi_anggota
0            10.0     0.0                     NaN
1            10.0     0.0                     NaN
2             5.0     0.0              2013-08-06
3             7.0     0.0                     NaN
4             8.0     0.0                     NaN

[5 rows x 33 columns]

In [4]:
import pandas as pd
import numpy as np

data_train = {
    'tahun_kelahiran': [1957, 1968, 1968, 1971, 1974],
    'pendidikan': ['Sarjana', 'Doktor', 'SMA', 'Doktor', 'Sarjana'],
    'status_pernikahan': [np.nan, 'Menikah', 'Menikah', 'Menikah', 'Rencana Menikah'],
    'pendapatan': [120660151.0, 163551821.0, 29857000.0, 117949098.0, 164761134.0],
    'jumlah_anak_balita': [0, 0, 0, 0, 0],
    'jumlah_anak_remaja': [1, 1, 0, 1, 0],
    'terakhir_belanja': [63, 58, 34, 82, 28],
    'belanja_buah': [122277, 35761, 8092, 4872, 343208],
    'belanja_daging': [541399, 353335, 22253, 126061, 1416462],
    'belanja_ikan': [214192, 63365, 30345, 0, 236196],
    'belanja_kue': [84305, 41112, 26299, 9745, 107776],
    'pembelian_diskon': [4, 2, 2, 3, 0],
    'pembelian_web': [6, 5, 0, 5, 1],
    'pembelian_toko': [10, 10, 5, 7, 8],
    'keluhan': [0, 0, 0, 0, 0],
    'tanggal_menjadi_anggota': [np.nan, np.nan, '2013-08-06', np.nan, np.nan]
}

data_test = {
    'tahun_kelahiran': [1979, 1950, 1966, 1961, 1970],
    'pendidikan': ['Sarjana', 'Sarjana', 'Sarjana', 'Magister', 'Sarjana'],
    'status_pernikahan': ['Rencana Menikah', 'Rencana Menikah', 'Menikah', 'Rencana Menikah', 'Rencana Menikah'],
    'pendapatan': [np.nan, 84063000.0, 127532564.0, 165579620.0, 117703159.0],
    'jumlah_anak_balita': [0, np.nan, 0, 0, 1],
    'jumlah_anak_remaja': [1, np.nan, 0, 0, 1],
    'terakhir_belanja': [np.nan, 70, 45, 90, 78],
    'belanja_buah': [50575, 6069, 117611, 206346, 90563],
    'belanja_daging': [260967, 44506, 265460, 1613901, 311757],
    'belanja_ikan': [50575, 80920, 96341, 27725, 40358],
    'belanja_kue': [20230, 20230, 145573, 125868, 33875],
    'pembelian_diskon': [2, 9, 1, 0, 7],
    'pembelian_web': [2, 6, 1, 7, 6],
    'pembelian_toko': [5, 4, 7, 8, 5],
    'keluhan': [0, 0, 0, 0, 0],
    'tanggal_menjadi_anggota': ['2014-05-05', '2013-03-17', np.nan, np.nan, np.nan]
}

df_train = pd.DataFrame(data_train)
df_test = pd.DataFrame(data_test)

print("Kolom data train:", df_train.columns)
print("Kolom data test:", df_test.columns)
print("\nMissing values data train:\n", df_train.isnull().sum())
print("\nMissing values data test:\n", df_test.isnull().sum())
print("\nStatistik deskriptif data train:\n", df_train.describe())
print("\nStatistik deskriptif data test:\n", df_test.describe())
print("\nDistribusi pendidikan (data train):\n", df_train['pendidikan'].value_counts())
print("\nDistribusi pendidikan (data test):\n", df_test['pendidikan'].value_counts())
print("\nDistribusi status pernikahan (data train features):\n", df_train['status_pernikahan'].value_counts(dropna=False))
print("\nDistribusi status pernikahan (data test features):\n", df_test['status_pernikahan'].value_counts(dropna=False))

numerik_train = df_train.select_dtypes(include=[np.number])
numerik_test = df_test.select_dtypes(include=[np.number])

print("\nKorelasi data train (kolom numerik):\n", numerik_train.corr())
print("\nKorelasi data test (kolom numerik):\n", numerik_test.corr())

Kolom data train: Index(['tahun_kelahiran', 'pendidikan', 'status_pernikahan', 'pendapatan',
       'jumlah_anak_balita', 'jumlah_anak_remaja', 'terakhir_belanja',
       'belanja_buah', 'belanja_daging', 'belanja_ikan', 'belanja_kue',
       'pembelian_diskon', 'pembelian_web', 'pembelian_toko', 'keluhan',
       'tanggal_menjadi_anggota'],
      dtype='object')
Kolom data test: Index(['tahun_kelahiran', 'pendidikan', 'status_pernikahan', 'pendapatan',
       'jumlah_anak_balita', 'jumlah_anak_remaja', 'terakhir_belanja',
       'belanja_buah', 'belanja_daging', 'belanja_ikan', 'belanja_kue',
       'pembelian_diskon', 'pembelian_web', 'pembelian_toko', 'keluhan',
       'tanggal_menjadi_anggota'],
      dtype='object')

Missing values data train:
 tahun_kelahiran            0
pendidikan                 0
status_pernikahan          1
pendapatan                 0
jumlah_anak_balita         0
jumlah_anak_remaja         0
terakhir_belanja           0
belanja_buah               0
belanja_daging             0
belanja_ikan               0
belanja_kue                0
pembelian_diskon           0
pembelian_web              0
pembelian_toko             0
keluhan                    0
tanggal_menjadi_anggota    4
dtype: int64

Missing values data test:
 tahun_kelahiran            0
pendidikan                 0
status_pernikahan          0
pendapatan                 1
jumlah_anak_balita         1
jumlah_anak_remaja         1
terakhir_belanja           1
belanja_buah               0
belanja_daging             0
belanja_ikan               0
belanja_kue                0
pembelian_diskon           0
pembelian_web              0
pembelian_toko             0
keluhan                    0
tanggal_menjadi_anggota    3
dtype: int64

Statistik deskriptif data train:
        tahun_kelahiran    pendapatan  jumlah_anak_balita  jumlah_anak_remaja  \
count         5.000000  5.000000e+00                 5.0            5.000000
mean       1967.600000  1.193558e+08                 0.0            0.600000
std           6.426508  5.483760e+07                 0.0            0.547723
min        1957.000000  2.985700e+07                 0.0            0.000000
25%        1968.000000  1.179491e+08                 0.0            0.000000
50%        1968.000000  1.206602e+08                 0.0            1.000000
75%        1971.000000  1.635518e+08                 0.0            1.000000
max        1974.000000  1.647611e+08                 0.0            1.000000

       terakhir_belanja   belanja_buah  belanja_daging   belanja_ikan  \
count          5.000000       5.000000    5.000000e+00       5.000000
mean          53.000000  102842.000000    4.919020e+05  108819.600000
std           22.090722  142503.576395    5.547233e+05  108851.020676
min           28.000000    4872.000000    2.225300e+04       0.000000
25%           34.000000    8092.000000    1.260610e+05   30345.000000
50%           58.000000   35761.000000    3.533350e+05   63365.000000
75%           63.000000  122277.000000    5.413990e+05  214192.000000
max           82.000000  343208.000000    1.416462e+06  236196.000000

         belanja_kue  pembelian_diskon  pembelian_web  pembelian_toko  keluhan
count       5.000000           5.00000       5.000000         5.00000      5.0
mean    53847.400000           2.20000       3.400000         8.00000      0.0
std     40933.133698           1.48324       2.701851         2.12132      0.0
min      9745.000000           0.00000       0.000000         5.00000      0.0
25%     26299.000000           2.00000       1.000000         7.00000      0.0
50%     41112.000000           2.00000       5.000000         8.00000      0.0
75%     84305.000000           3.00000       5.000000        10.00000      0.0
max    107776.000000           4.00000       6.000000        10.00000      0.0

Statistik deskriptif data test:
        tahun_kelahiran    pendapatan  jumlah_anak_balita  jumlah_anak_remaja  \
count         5.000000  4.000000e+00                4.00             4.00000
mean       1965.200000  1.237196e+08                0.25             0.50000
std          10.756393  3.354422e+07                0.50             0.57735
min        1950.000000  8.406300e+07                0.00             0.00000
25%        1961.000000  1.092931e+08                0.00             0.00000
50%        1966.000000  1.226179e+08                0.00             0.50000
75%        1970.000000  1.370443e+08                0.25             1.00000
max        1979.000000  1.655796e+08                1.00             1.00000

       terakhir_belanja   belanja_buah  belanja_daging  belanja_ikan  \
count          4.000000       5.000000    5.000000e+00       5.00000
mean          70.750000   94232.800000    4.993182e+05   59183.80000
std           19.032866   75511.979865    6.316306e+05   28597.63182
min           45.000000    6069.000000    4.450600e+04   27725.00000
25%           63.750000   50575.000000    2.609670e+05   40358.00000
50%           74.000000   90563.000000    2.654600e+05   50575.00000
75%           81.000000  117611.000000    3.117570e+05   80920.00000
max           90.000000  206346.000000    1.613901e+06   96341.00000

         belanja_kue  pembelian_diskon  pembelian_web  pembelian_toko  keluhan
count       5.000000          5.000000       5.000000        5.000000      5.0
mean    69155.200000          3.800000       4.400000        5.800000      0.0
std     61416.741901          3.962323       2.701851        1.643168      0.0
min     20230.000000          0.000000       1.000000        4.000000      0.0
25%     20230.000000          1.000000       2.000000        5.000000      0.0
50%     33875.000000          2.000000       6.000000        5.000000      0.0
75%    125868.000000          7.000000       6.000000        7.000000      0.0
max    145573.000000          9.000000       7.000000        8.000000      0.0

Distribusi pendidikan (data train):
 pendidikan
Sarjana    2
Doktor     2
SMA        1
Name: count, dtype: int64

Distribusi pendidikan (data test):
 pendidikan
Sarjana     4
Magister    1
Name: count, dtype: int64

Distribusi status pernikahan (data train features):
 status_pernikahan
Menikah            3
NaN                1
Rencana Menikah    1
Name: count, dtype: int64

Distribusi status pernikahan (data test features):
 status_pernikahan
Rencana Menikah    4
Menikah            1
Name: count, dtype: int64

Korelasi data train (kolom numerik):
                     tahun_kelahiran  pendapatan  jumlah_anak_balita  \
tahun_kelahiran            1.000000    0.180089                 NaN
pendapatan                 0.180089    1.000000                 NaN
jumlah_anak_balita              NaN         NaN                 NaN
jumlah_anak_remaja        -0.482962    0.367008                 NaN
terakhir_belanja          -0.304650    0.156549                 NaN
belanja_buah               0.255105    0.530816                 NaN
belanja_daging             0.273874    0.644879                 NaN
belanja_ikan              -0.257778    0.464413                 NaN
belanja_kue               -0.136633    0.495964                 NaN
pembelian_diskon          -0.802555   -0.275423                 NaN
pembelian_web             -0.550005    0.450816                 NaN
pembelian_toko            -0.458457    0.775616                 NaN
keluhan                         NaN         NaN                 NaN

                    jumlah_anak_remaja  terakhir_belanja  belanja_buah  \
tahun_kelahiran              -0.482962         -0.304650      0.255105
pendapatan                    0.367008          0.156549      0.530816
jumlah_anak_balita                 NaN               NaN           NaN
jumlah_anak_remaja            1.000000          0.909122     -0.466404
terakhir_belanja              0.909122          1.000000     -0.571082
belanja_buah                 -0.466404         -0.571082      1.000000
belanja_daging               -0.374308         -0.509985      0.989344
belanja_ikan                 -0.205056         -0.418231      0.867259
belanja_kue                  -0.294159         -0.515035      0.914595
pembelian_diskon              0.738549          0.755360     -0.638501
pembelian_web                 0.979819          0.858663     -0.304059
pembelian_toko                0.645497          0.309422      0.237291
keluhan                            NaN               NaN           NaN

                    belanja_daging  belanja_ikan  belanja_kue  \
tahun_kelahiran           0.273874     -0.257778    -0.136633
pendapatan                0.644879      0.464413     0.495964
jumlah_anak_balita             NaN           NaN          NaN
jumlah_anak_remaja       -0.374308     -0.205056    -0.294159
terakhir_belanja         -0.509985     -0.418231    -0.515035
belanja_buah              0.989344      0.867259     0.914595
belanja_daging            1.000000      0.852683     0.905080
belanja_ikan              0.852683      1.000000     0.988560
belanja_kue               0.905080      0.988560     1.000000
pembelian_diskon         -0.642926     -0.236645    -0.374893
pembelian_web            -0.216926     -0.009997    -0.107407
pembelian_toko            0.339208      0.502450     0.466969
keluhan                        NaN           NaN          NaN

                    pembelian_diskon  pembelian_web  pembelian_toko  keluhan
tahun_kelahiran            -0.802555      -0.550005       -0.458457      NaN
pendapatan                 -0.275423       0.450816        0.775616      NaN
jumlah_anak_balita               NaN            NaN             NaN      NaN
jumlah_anak_remaja          0.738549       0.979819        0.645497      NaN
terakhir_belanja            0.755360       0.858663        0.309422      NaN
belanja_buah               -0.638501      -0.304059        0.237291      NaN
belanja_daging             -0.642926      -0.216926        0.339208      NaN
belanja_ikan               -0.236645      -0.009997        0.502450      NaN
belanja_kue                -0.374893      -0.107407        0.466969      NaN
pembelian_diskon            1.000000       0.723644        0.238366      NaN
pembelian_web               0.723644       1.000000        0.741517      NaN
pembelian_toko              0.238366       0.741517        1.000000      NaN
keluhan                          NaN            NaN             NaN      NaN

Korelasi data test (kolom numerik):
                     tahun_kelahiran  pendapatan  jumlah_anak_balita  \
tahun_kelahiran            1.000000    0.460540            0.087538
pendapatan                 0.460540    1.000000           -0.658788
jumlah_anak_balita         0.087538   -0.658788            1.000000
jumlah_anak_remaja         0.833908   -0.658788            0.577350
terakhir_belanja          -0.111794    0.362207            0.260153
belanja_buah               0.082434    0.999632           -0.259465
belanja_daging            -0.078919    0.905014           -0.300821
belanja_ikan              -0.306968   -0.587332           -0.298663
belanja_kue               -0.105169    0.753970           -0.498824
pembelian_diskon          -0.438758   -0.887457            0.964901
pembelian_web             -0.545382    0.083647            0.452911
pembelian_toko             0.059407    0.940855           -0.555556
keluhan                         NaN         NaN                 NaN

                    jumlah_anak_remaja  terakhir_belanja  belanja_buah  \
tahun_kelahiran           8.339078e-01         -0.111794      0.082434
pendapatan               -6.587882e-01          0.362207      0.999632
jumlah_anak_balita        5.773503e-01          0.260153     -0.259465
jumlah_anak_remaja        1.000000e+00          0.260153     -0.798887
terakhir_belanja          2.601530e-01          1.000000      0.338688
belanja_buah             -7.988874e-01          0.338688      1.000000
belanja_daging           -5.649588e-01          0.649977      0.894654
belanja_ikan             -3.199669e-01         -0.922827     -0.478093
belanja_kue              -9.880554e-01         -0.302050      0.793693
pembelian_diskon          7.427814e-01          0.072226     -0.737878
pembelian_web            -4.354653e-17          0.957162      0.208131
pembelian_toko           -9.622504e-01          0.067148      0.949517
keluhan                            NaN               NaN           NaN

                    belanja_daging  belanja_ikan  belanja_kue  \
tahun_kelahiran          -0.078919     -0.306968    -0.105169
pendapatan                0.905014     -0.587332     0.753970
jumlah_anak_balita       -0.300821     -0.298663    -0.498824
jumlah_anak_remaja       -0.564959     -0.319967    -0.988055
terakhir_belanja          0.649977     -0.922827    -0.302050
belanja_buah              0.894654     -0.478093     0.793693
belanja_daging            1.000000     -0.665110     0.553394
belanja_ikan             -0.665110      1.000000     0.153338
belanja_kue               0.553394      0.153338     1.000000
pembelian_diskon         -0.611014      0.184853    -0.728079
pembelian_web             0.474237     -0.591490    -0.195366
pembelian_toko            0.802323     -0.222375     0.921291
keluhan                        NaN           NaN          NaN

                    pembelian_diskon  pembelian_web  pembelian_toko  keluhan
tahun_kelahiran            -0.438758  -5.453824e-01        0.059407      NaN
pendapatan                 -0.887457   8.364745e-02        0.940855      NaN
jumlah_anak_balita          0.964901   4.529108e-01       -0.555556      NaN
jumlah_anak_remaja          0.742781  -4.354653e-17       -0.962250      NaN
terakhir_belanja            0.072226   9.571622e-01        0.067148      NaN
belanja_buah               -0.737878   2.081311e-01        0.949517      NaN
belanja_daging             -0.611014   4.742370e-01        0.802323      NaN
belanja_ikan                0.184853  -5.914901e-01       -0.222375      NaN
belanja_kue                -0.728079  -1.953662e-01        0.921291      NaN
pembelian_diskon            1.000000   4.063292e-01       -0.852435      NaN
pembelian_web               0.406329   1.000000e+00       -0.033787      NaN
pembelian_toko             -0.852435  -3.378687e-02        1.000000      NaN
keluhan                          NaN            NaN             NaN      NaN


### Distribusi daari segi Pendidikan
Data Train:
Pendidikan didominasi oleh lulusan Sarjana dan Doktor dengan satu responden yang hanya berpendidikan SMA.

Data Test:
Tidak ada responden dengan pendidikan SMA. Mayoritas berpendidikan Sarjana, dengan satu responden berpendidikan Magister.

Perbedaan:

Data train mencakup individu dengan tingkat pendidikan yang lebih rendah (SMA), sementara data test hanya mencakup orang dengan pendidikan lebih tinggi (Sarjana dan Magister). Ini menunjukkan ada perbedaan profil pendidikan antara kedua dataset.
### Distribusi dari Status Pernikahan

Data Train:
Terdapat 3 responden yang sudah Menikah, 1 responden yang Rencana Menikah, dan 1 data yang hilang (NaN).

Data Test:
Didominasi oleh responden yang berstatus Rencana Menikah (4 responden), dan hanya 1 responden yang sudah Menikah.

Perbedaan:

Data train lebih seimbang dalam hal status pernikahan, sedangkan data test mayoritas terdiri dari responden yang berencana menikah. Ini mengindikasikan perbedaan signifikan dalam status hubungan di antara kedua dataset.

### statistik Deskriptif Kolom Numerik
Pendapatan:

Data Train: Pendapatan berkisar antara 29.857.000 hingga 164.761.000 dengan rata-rata 119.355.800.

Data Test: Pendapatan berkisar antara 84.063.000 hingga 165.579.600 dengan rata-rata 123.719.600.
Perbedaan:

Meskipun rata-rata pendapatan pada kedua dataset tidak terlalu berbeda, nilai minimum pendapatan pada data test lebih tinggi dibandingkan data train, yang mungkin menunjukkan bahwa responden dalam data test secara umum memiliki pendapatan yang lebih tinggi.

### Jumlah Anak Balita:

Data Train: Semua responden memiliki 0 anak balita.

Data Test: Beberapa responden memiliki anak balita (hingga 1 anak).
Perbedaan:

Data test mengandung lebih banyak variasi dalam hal jumlah anak balita dibandingkan data train, yang hanya terdiri dari responden tanpa anak balita.
### Kehilangan Data (Missing Values)
Data Train:
Missing values pada status_pernikahan (1 data hilang) dan tanggal_menjadi_anggota (4 data hilang).

Data Test:
Missing values pada pendapatan, jumlah_anak_balita, jumlah_anak_remaja, terakhir_belanja, dan tanggal_menjadi_anggota.
Perbedaan:

Data test memiliki lebih banyak missing values pada kolom numerik, sedangkan data train lebih sedikit kehilangan data pada kolom-kolom ini. Ini dapat mempengaruhi kualitas model prediksi jika tidak ditangani dengan baik.